# Generated by Django 4.2.4 on 2023-08-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='politician_images/')),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='politician_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='politician_images/')),
                ('district', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='politician_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
