# Generated by Django 4.1.7 on 2023-02-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliticianModel',
            new_name='Politician',
        ),
    ]
