# Generated by Django 4.1.7 on 2023-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_rename_politicianmodel_politician'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
