stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  MAVERICK_IMAGE_NAME: registry.gitlab.com/mcguire001/blackbird/maverick
  BLACKBIRD_IMAGE_NAME: registry.gitlab.com/mcguire001/blackbird/blackbird

image:            # Official docker compose image.
  name: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-front-end:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building Frontend..."
    - docker build -t $MAVERICK_IMAGE_NAME ./maverick
    - docker push $MAVERICK_IMAGE_NAME

build-back-end:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building Backend..."
    - docker build -t $BLACKBIRD_IMAGE_NAME ./blackbird
    - docker push $BLACKBIRD_IMAGE_NAME

font-end-test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Pulling Frontend Image..."
    - docker pull $MAVERICK_IMAGE_NAME:latest
    - echo "Running unit tests..."
    - docker run $MAVERICK_IMAGE_NAME:latest npm run test-all

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
