# Generated by Django 4.1.7 on 2023-03-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('politicians', '0004_representative_senator_rename_politician_president'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='politicians.representative')),
            ],
        ),
    ]
