# Generated by Django 4.2.4 on 2023-08-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.CharField(max_length=25)),
                ('first_session', models.CharField(max_length=50)),
                ('second_session', models.CharField(max_length=50)),
            ],
        ),
    ]
